export const endPoint = {
  Agency: "/api/agency", //
  Brand: "/api/brand",
  Camera: "/api/camera",
  CameraOnly: "/api/camera/only",
  Server: "/api/server",
  Hikvision: "/api/deviceinfo/hikvision",
  Vivotek: "/api/deviceinfo/vivotek",
  CamImageHik: "/api/DeviceInfo/hik/image",
  HikTime: "/api/hikvision/time",
  Capabilities: "/api/Hikvision/capabilities",
  Log: "/api/Log",
  //LogPost: "/api/Log",
  LogServer: "/api/Logserver/server",
  LogPostServer: "/api/Logserver",
  FilePost: "/api/server/file",
  HikName: "/api/Hikvision/info",
  hikdatasheet: "/api/datasheet",
  hikChannelStatus: "/api/hikvision/channels",
  DataPdf: "/pdf/datasheet",
  vivotek: "/api/vivotek",
  evento: "/api/evento",
  hik: "/api/hikvision",
  geovision: "/api/geovision",
  panasonic: "/api/panasonic",
  datasheet: "/api/datasheet",
};
