export default {
  id: 0,
  agenciaId: 0,
  name: "",
  user: "",
  password: "",
  ubicacionFisica: "",
  ubicacionConexion: "",
  patchPanel: "",
  switch: "",
  portPatchPanel: 0,
  portSwitch: 0,
  type: "",
  brandId: 0,
  model: "",
  ipAddress: "",
  nota: "",
  mac: "",
  deviceId: "",
  deviceDescription: "",
  serialNumber: "",
  firmwareVersion: "",
  isGoodCondition: true,
  fechaInstalacion: new Date(),
  fechaCompra: new Date(),
  serverId: 0,
};
