export default {
  name: "",
  user: "",
  password: "",
  location: "",
  locationConnection: "",
  idPatchPanel: "",
  idSwitch: "",
  portPatchPanel: 0,
  portSwitch: 0,
  type: "",
  brandId: 0,
  model: "",
  ipAddress: "",
  mac: "",
  deviceId: "",
  deviceDescription: "",
  serialNumber: "",
  firmwareVersion: "",
  isGoodCondition: true,
  dateInstallation: "2022-03-23T17:46:40.041Z",
  dateBuys: "2022-03-23T17:46:40.041Z",
  serverId: 0,
};
