export default {
  agenciaId: 0,
  assetId: "",
  brandId: 0,
  deviceDescription: "",
  deviceId: "",
  fechaCompra: new Date(),
  fechaInstalacion: new Date(),
  firmwareVersion: "",
  id: 0,
  ipAddress: "",
  onLine: true,
  retired: false,
  mac: "",
  model: "",
  name: "",
  nota: "",
  password: "",
  patchPanel: "",
  portPatchPanel: 0,
  portSwitch: 0,
  serialNumber: "",
  serverId: 0,
  type: "",
  ubicacionConexion: "",
  ubicacionFisica: "",
  user: "",
  switch: "",
};
