export default {
  name: "",
  user: "",
  password: "",
  location: "",
  type: "",
  brandId: 0,
  model: "",
  cameraCapacity: 0,
  cameraAvailable: 0,
  storage: "",
  storageAvailable: "",
  engravedDays: 0,
  ipAddress: "",
  mac: "",
  deviceId: "",
  serialNumber: "",
  firmwareVersion: "",
  isGoodCondition: true,
  dateInstallation: "2022-03-23T17:46:40.041Z",
  dateBuys: "2022-03-23T17:46:40.041Z",
  agenciaId: 0,
};
