export default {
  assetId: "",
  agenciaId: 0,
  brand: null,
  brandId: 0,
  canalesIP: 0,
  capacidadSata: 0,
  capacidadSataInstalado: 0,
  deviceId: "",
  engravedDays: 0,
  fechaCompra: new Date(),
  fechaInstalacion: new Date(),
  firmwareVersion: "",
  id: 0,
  ipAddress: "",
  onLine: true,
  retired: false,
  mac: "",
  modelo: "",
  nombre: "",
  nota: "",
  password: "",
  portAnalogo: 0,
  portIpPoe: 0,
  sata: 0,
  sataInstalado: 0,
  serialNumber: "",
  type: "",
  ubicacion: "",
  user: "",
};
