export default {
  id: 0,
  brand: "",
  nombre: "",
  user: "",
  password: "",
  ubicacion: "",
  type: "",
  modelo: "",
  mac: "",
  deviceId: "",
  serialNumber: "",
  firmwareVersion: "",
  ipAddress: "",
  sata: 0,
  capacidadSata: 0,
  sataInstalado: 0,
  capacidadSataInstalado: 0,
  engravedDays: 0,
  isGoodCondition: true,
  portAnalogo: 0,
  portIpPoe: 0,
  canalesIP: 0,
  nota: "",
  fechaInstalacion: "2022-06-08T21:14:39.433Z",
  fechaCompra: "2022-06-08T21:14:39.433Z",
  brandId: 0,
};
