INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2121G0-I.pdf', 1)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1023G0E-I.pdf', 2)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2020-I.pdf', 4)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2020-I.pdf', 5)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8161.pdf', 6)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'M1114.pdf', 7)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2955FWD-IS.pdf', 21)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2942F-I.pdf', 3)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2020-I.pdf', 8)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2020-I.pdf', 9)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2020-I.pdf', 10)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1123G0E-I.pdf', 11)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD6362F-IS.pdf', 12)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2020-I.pdf', 13)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2020-I.pdf', 14)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2020-I.pdf', 15)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 16)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 17)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 18)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 19)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 20)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2955FWD-IS.pdf', 22)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 23)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 26)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 27)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 28)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'SD83X3.pdf', 29)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'SD83X3.pdf', 30)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IP7361.pdf', 31)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8161.pdf', 32)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 33)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 34)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 35)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8161.pdf', 36)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 37)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 38)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8161.pdf', 39)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 40)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8167.pdf', 41)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 42)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 43)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 44)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 45)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 46)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8161.pdf', 47)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8161.pdf', 48)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 49)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 50)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 51)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 52)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 53)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 54)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 55)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 56)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 57)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 58)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 58)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8161.pdf', 59)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 60)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IP7361.pdf', 61)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'IP7361.pdf', 62)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'IP7361.pdf', 63)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IP7361.pdf', 64)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IB8369A.pdf', 65)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IP7361.pdf', 66)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IB8367A.pdf', 67)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IP7361.pdf', 68)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 69)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 70)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 71)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'FE8172V.pdf', 72)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'FE8172V.pdf', 73)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 74)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 75)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 76)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 77)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 78)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8136.pdf', 79)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 80)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 81)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'FD8134.pdf', 82)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'FD9360-H.pdf', 83)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD9360-H.pdf', 83)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 84)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD8134.pdf', 85)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IB8369A.pdf', 86)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IB9380-H.pdf', 87)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IP7361.pdf', 88)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 89)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 90)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'FD8134.pdf', 91)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'IP7361.pdf', 92)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 93)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 94)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 95)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 96)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IP7361.pdf', 97)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IB8369.pdf', 98)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FE8172V.pdf', 99)
GO
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IP7361.pdf', 100)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'IP7361.pdf', 101)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'IP7361.pdf', 102)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IB8369A.pdf', 103)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IP7361.pdf', 104)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IB8369.pdf', 105)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD9360-H.pdf', 106)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'CC8160.pdf', 107)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IB9380-H.pdf', 321)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 116)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1023G0E-I.pdf', 173)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'ECI-D12F2.pdf', 174)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 176)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-EFD1100.pdf', 178)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-EFD1100.pdf', 179)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-FE2301.pdf', 180)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-FE2301.pdf', 181)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-MFD130.pdf', 182)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-MFD130.pdf', 183)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-FE520-FE521.pdf', 184)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 185)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C131A.pdf', 187)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-VT164.pdf', 188)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-VT164.pdf', 189)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 190)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C131A.pdf', 191)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C131A.pdf', 192)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 194)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 193)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 223)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 224)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 195)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-VT164.pdf', 212)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-FE520-FE521.pdf', 210)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-FE520-FE521.pdf', 211)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-FD2400.pdf', 257)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 258)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 303)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 304)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 259)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-MFD130.pdf', 323)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C131A.pdf', 322)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-C210.pdf', 271)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'BL-VT164.pdf', 186)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-BL1200.pdf', 221)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-BL1200.pdf', 222)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1643G0-IZ.pdf', 319)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1643G0-IZ.pdf', 320)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 117)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 118)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 119)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 120)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 121)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 122)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 123)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1121-I.pdf', 124)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD6362F-IS.pdf', 125)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1121-I.pdf', 126)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 127)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1121-I.pdf', 128)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 129)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'DT2A404.pdf', 130)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'DS-2CD1043G0E-I.pdf', 131)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 132)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 133)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2121G0-I.pdf', 134)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1123G0E-I.pdf', 135)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1123G0E-I.pdf', 136)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2121G0-I.pdf', 137)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1123G0E-I.pdf', 138)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2121G0-I.pdf', 139)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'DS-2CD1123G0E-I.pdf', 140)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'DS-2CD1023G0E-I.pdf', 141)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1023G0E-I.pdf', 142)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 141)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 142)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 143)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 144)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 145)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 146)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 147)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'DS-2CD1043G0E-I.pdf', 148)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'DS-2CD1043G0E-I.pdf', 149)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 150)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 151)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2955FWD-IS.pdf', 152)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 153)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 154)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 155)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 156)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1043G0E-I.pdf', 157)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'DS-2CD1043G0E-I.pdf', 158)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'DS-2CD2021G1-I.pdf', 159)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2121G0-I.pdf', 160)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 247)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 248)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 249)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 250)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 250)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 251)
GO
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 252)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'DS-2CD2021G1-I.pdf', 253)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES ( N'DS-2CD2021G1-I.pdf', 254)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2121G0-I.pdf', 255)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2121G0-I.pdf', 253)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD2021G1-I.pdf', 256)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1023G0E-I.pdf', 260)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1023G0E-I.pdf', 261)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1023G0E-I.pdf', 262)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1023G0E-I.pdf', 263)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1023G0E-I.pdf', 264)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1023G0E-I.pdf', 265)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1023G0E-I.pdf', 266)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 268)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'DS-2CD1021-I.pdf', 269)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IP8331.pdf', 325)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IP8331.pdf', 324)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'GV-EFD1100.pdf', 330)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD9380-H.pdf', 328)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'FD9380-H.pdf', 329)
INSERT [dbo].[CameraDataSheets] ( [DataSheetName], [CameraId]) VALUES (N'IB9380-H.pdf', 331)